server:
  port: 8012
  servlet:
    context-path: /Gateway

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/act5?characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong&nullCatalogMeansCurrent=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write_dates_as_timestamps: false

mybatis-plus: #下划线转驼峰关闭
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true

tool:
  download-timeout: 5m
  doc-disabled: false
  production-env: false
  auth-enabled: true
  mode: demo
  workDir: ${user.home}/tool-demo/
  cache: memory
